# msrchd service module - Multi-project support
# Hosts multiple msrchd instances at *.msrchd.domain
# Each project has its own db.sqlite, shares code via symlinks

{ config, lib, pkgs, domain, srchdAuth, ... }:

let
  nodejs = pkgs.nodejs_22;

  # Directories
  msrchdBase = "/var/lib/msrchd";           # Base installation (code + node_modules)
  projectsDir = "/var/lib/msrchd-projects"; # Per-project directories
  acmeChallengeDir = "/var/lib/acme/acme-challenge";
  basePort = 13380;                        # Base port for projects (different from srchd)

  # Auth args
  authArgs = if srchdAuth != "" then "-a ${srchdAuth}" else "";

  # Discovery script - manages projects, services, and nginx config
  discoveryScript = pkgs.writeShellScriptBin "msrchd-discover" ''
    set -e

    MSRCHD_BASE="${msrchdBase}"
    PROJECTS_DIR="${projectsDir}"
    BASE_PORT=${toString basePort}
    NGINX_CONF="/etc/nginx/msrchd-projects.conf"
    INDEX_FILE="${msrchdBase}/index.html"
    ACME_CHALLENGE="${acmeChallengeDir}"

    # Files to symlink from base installation
    SYMLINK_FILES="node_modules src package.json package-lock.json tsconfig.json drizzle.config.ts"

    echo "=== msrchd Discovery ==="

    # Ensure directories exist
    mkdir -p "$PROJECTS_DIR" "$ACME_CHALLENGE"

    # Find all projects (directories containing db.sqlite)
    PROJECTS=""
    declare -A PROJECT_PORTS
    port_counter=0

    for dir in "$PROJECTS_DIR"/*/; do
      [ -d "$dir" ] || continue
      project=$(basename "$dir")
      if [ -f "$dir/db.sqlite" ]; then
        echo "Found project: $project"
        PROJECTS="$PROJECTS $project"

        # Get or assign port
        if [ -f "$dir/.port" ]; then
          port=$(cat "$dir/.port")
        else
          port=$((BASE_PORT + port_counter))
          echo "$port" > "$dir/.port"
        fi
        PROJECT_PORTS[$project]=$port
        port_counter=$((port_counter + 1))
        echo "  Port: $port"

        # Ensure publications directory exists
        mkdir -p "$dir/publications"

        # Set up symlinks if not present
        for file in $SYMLINK_FILES; do
          if [ -e "$MSRCHD_BASE/$file" ] && [ ! -e "$dir/$file" ]; then
            ln -sf "$MSRCHD_BASE/$file" "$dir/$file"
            echo "  Linked $file"
          fi
        done

        # Start service if not running
        if ! systemctl is-active --quiet "msrchd@$project"; then
          echo "  Starting msrchd@$project"
          systemctl start "msrchd@$project" || true
        fi
      fi
    done

    # Stop services for removed projects
    for service in $(systemctl list-units --type=service --state=running --no-legend | grep '^msrchd@' | awk '{print $1}'); do
      project=$(echo "$service" | sed 's/msrchd@\(.*\)\.service/\1/')
      if [ ! -f "$PROJECTS_DIR/$project/db.sqlite" ]; then
        echo "Stopping removed project: $project"
        systemctl stop "$service" || true
      fi
    done

    # Generate nginx config
    echo "Generating nginx config..."
    cat > "$NGINX_CONF" << 'NGINX_HEADER'
# Auto-generated by msrchd-discover - DO NOT EDIT
NGINX_HEADER

    for project in $PROJECTS; do
      port=''${PROJECT_PORTS[$project]}
      subdomain="$project.msrchd.${domain}"
      cert_dir="/var/lib/acme/$subdomain"
      has_cert="false"

      if [ -f "$cert_dir/fullchain.pem" ] && [ -f "$cert_dir/key.pem" ]; then
        has_cert="true"
      fi

      cat >> "$NGINX_CONF" << NGINX_PROJECT

# Project: $project
upstream msrchd_$project {
    server [::1]:$port;
}

server {
    listen 80;
    listen [::]:80;
    server_name $subdomain;

    # ACME challenge location
    location /.well-known/acme-challenge/ {
        root $ACME_CHALLENGE;
    }

NGINX_PROJECT

      if [ "$has_cert" = "true" ]; then
        cat >> "$NGINX_CONF" << NGINX_REDIRECT
    # Redirect to HTTPS
    location / {
        return 301 https://\$server_name\$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name $subdomain;

    ssl_certificate $cert_dir/fullchain.pem;
    ssl_certificate_key $cert_dir/key.pem;

    location / {
        proxy_pass http://msrchd_$project;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX_REDIRECT
      else
        # No cert yet - serve via HTTP and proxy (for cert acquisition)
        cat >> "$NGINX_CONF" << NGINX_HTTP_ONLY
    # No cert yet - serving via HTTP
    location / {
        proxy_pass http://msrchd_$project;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX_HTTP_ONLY
      fi
    done

    # Reload nginx first (needed for ACME challenges)
    echo "Reloading nginx..."
    systemctl reload nginx || echo "WARNING: nginx reload failed"

    # Request certificates for projects that don't have them
    for project in $PROJECTS; do
      subdomain="$project.msrchd.${domain}"
      cert_dir="/var/lib/acme/$subdomain"

      if [ ! -f "$cert_dir/fullchain.pem" ]; then
        echo "Requesting certificate for $subdomain..."
        mkdir -p "$cert_dir"

        # Use certbot with webroot
        ${pkgs.certbot}/bin/certbot certonly \
          --webroot -w "$ACME_CHALLENGE" \
          -d "$subdomain" \
          --non-interactive --agree-tos \
          --email "security@${domain}" \
          --deploy-hook "systemctl reload nginx" \
          2>&1 || echo "  (Certificate request failed - check DNS for $subdomain)"

        # Certbot stores certs in /etc/letsencrypt, copy them (symlinks don't work due to permissions)
        if [ -d "/etc/letsencrypt/live/$subdomain" ]; then
          cp "/etc/letsencrypt/live/$subdomain/fullchain.pem" "$cert_dir/fullchain.pem"
          cp "/etc/letsencrypt/live/$subdomain/privkey.pem" "$cert_dir/key.pem"
          chmod 644 "$cert_dir/fullchain.pem"
          chmod 640 "$cert_dir/key.pem"
          chown root:nginx "$cert_dir/key.pem"
          echo "  Certificate obtained!"
        fi
      fi
    done

    # Regenerate nginx config now that we might have new certs
    # (Re-run the config generation)
    cat > "$NGINX_CONF" << 'NGINX_HEADER2'
# Auto-generated by msrchd-discover - DO NOT EDIT
NGINX_HEADER2

    for project in $PROJECTS; do
      port=''${PROJECT_PORTS[$project]}
      subdomain="$project.msrchd.${domain}"
      cert_dir="/var/lib/acme/$subdomain"
      has_cert="false"

      if [ -f "$cert_dir/fullchain.pem" ] && [ -f "$cert_dir/key.pem" ]; then
        has_cert="true"
      fi

      cat >> "$NGINX_CONF" << NGINX_PROJECT2

# Project: $project
upstream msrchd_$project {
    server [::1]:$port;
}

server {
    listen 80;
    listen [::]:80;
    server_name $subdomain;

    location /.well-known/acme-challenge/ {
        root $ACME_CHALLENGE;
    }

NGINX_PROJECT2

      if [ "$has_cert" = "true" ]; then
        cat >> "$NGINX_CONF" << NGINX_REDIRECT2
    location / {
        return 301 https://\$server_name\$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name $subdomain;

    ssl_certificate $cert_dir/fullchain.pem;
    ssl_certificate_key $cert_dir/key.pem;

    location / {
        proxy_pass http://msrchd_$project;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX_REDIRECT2
      else
        cat >> "$NGINX_CONF" << NGINX_HTTP_ONLY2
    location / {
        proxy_pass http://msrchd_$project;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX_HTTP_ONLY2
      fi
    done

    # Final nginx reload
    echo "Final nginx reload..."
    systemctl reload nginx || echo "WARNING: nginx reload failed"

    # Generate index page (matching anas.lecaillon.com style)
    echo "Generating index page..."
    cat > "$INDEX_FILE" << 'INDEX_HEADER'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>msrchd - Experiments</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Crimson+Text:wght@400;600;700&family=Inter:wght@400;500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
  <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js" onload="renderMathInElement(document.body, {delimiters: [{left: '$$', right: '$$', display: true}, {left: '$', right: '$', display: false}]});"></script>
  <style>
    body {
      font-family: "Crimson Text", serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 40px 60px;
      text-align: center;
      background-color: #0f0f0f;
      color: #e8e8e8;
      line-height: 1.6;
    }
    a { color: #b8b8b8; text-decoration: none; transition: color 0.2s ease; }
    a:hover { color: #fff; }
    h1 {
      font-size: 2.2em;
      font-weight: 400;
      letter-spacing: 0.05em;
      margin: 20px 0 10px;
      color: #fff;
    }
    h2 {
      font-size: 1.4em;
      font-weight: 400;
      letter-spacing: 0.05em;
      margin: 30px 0 20px;
      color: #c0c0c0;
    }
    .nav {
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 1px solid rgba(255, 255, 255, 0.1);
    }
    .nav a {
      color: #888;
      margin: 0 20px;
      font-size: 1em;
      font-family: 'Inter', -apple-system, sans-serif;
    }
    .nav a:hover { color: #fff; }
    .nav a.active { color: #fff; }

    /* Tab content */
    .tab-content { display: none; }
    .tab-content.active { display: block; }

    /* Projects list */
    .projects {
      display: flex;
      flex-direction: column;
      gap: 20px;
      max-width: 800px;
      margin: 0 auto;
      text-align: left;
    }
    .project {
      background: rgba(255, 255, 255, 0.03);
      border: 1px solid rgba(255, 255, 255, 0.1);
      border-radius: 8px;
      overflow: hidden;
      transition: border-color 0.2s ease;
    }
    .project:hover { border-color: rgba(255, 255, 255, 0.2); }
    .project-header {
      padding: 20px 25px;
      cursor: pointer;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .project-title {
      font-family: 'Inter', -apple-system, sans-serif;
      font-size: 1.1em;
      font-weight: 500;
      color: #fff;
    }
    .project-title .icon { margin-right: 12px; color: #888; }
    .project-toggle {
      color: #666;
      transition: transform 0.2s ease, color 0.2s ease;
    }
    .project.expanded .project-toggle { transform: rotate(180deg); color: #888; }
    .project-body {
      max-height: 0;
      overflow: hidden;
      transition: max-height 0.3s ease;
      background: rgba(0, 0, 0, 0.2);
    }
    .project.expanded .project-body { max-height: 2000px; }
    .project-description {
      padding: 20px 25px;
      color: #aaa;
      font-size: 0.95em;
      border-top: 1px solid rgba(255, 255, 255, 0.05);
    }
    .project-description h3 { color: #fff; font-size: 1.1em; margin: 1.2em 0 0.5em; font-weight: 600; }
    .project-description h4 { color: #ddd; font-size: 1em; margin: 1em 0 0.4em; font-weight: 600; }
    .project-description p { margin: 0.8em 0; line-height: 1.7; }
    .project-description ul { padding-left: 1.5em; margin: 0.5em 0; }
    .project-description li { margin: 0.4em 0; }
    .project-description strong { color: #fff; }
    .project-description a { color: #7eb8da; }
    .project-description a:hover { color: #a8d4f0; }
    .project-description code {
      background: rgba(255, 255, 255, 0.1);
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 0.9em;
    }
    .project-link {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      margin-top: 15px;
      padding: 10px 18px;
      background: rgba(255, 255, 255, 0.08);
      border-radius: 6px;
      color: #fff;
      font-family: 'Inter', -apple-system, sans-serif;
      font-size: 0.9em;
      transition: background 0.2s ease;
    }
    .project-link:hover { background: rgba(255, 255, 255, 0.15); color: #fff; }
    .no-ssl { color: #cc6600; font-size: 0.8em; margin-left: 10px; }
    .empty { color: #666; font-style: italic; }

    /* About section */
    .about {
      max-width: 800px;
      margin: 0 auto;
      text-align: left;
    }
    .about p { margin: 1em 0; color: #bbb; }
    .about h3 { color: #fff; margin: 1.5em 0 0.5em; font-weight: 500; }
    .about ul { color: #bbb; padding-left: 1.5em; }
    .about li { margin: 0.5em 0; }
    .about code {
      background: rgba(255, 255, 255, 0.1);
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 0.9em;
    }
  </style>
</head>
<body>
  <h1>msrchd</h1>
  <nav class="nav">
    <a href="https://anas.lecaillon.com"><i class="fas fa-home"></i> Home</a>
    <a href="#experiments" class="tab-link active" data-tab="experiments"><i class="fas fa-flask"></i> Experiments</a>
    <a href="#about" class="tab-link" data-tab="about"><i class="fas fa-info-circle"></i> About</a>
    <a href="https://github.com/anonx3247/msrchd"><i class="fab fa-github"></i> GitHub</a>
  </nav>

  <div id="experiments" class="tab-content active">
    <h2>Experiments</h2>
    <div class="projects">
INDEX_HEADER

    for project in $PROJECTS; do
      subdomain="$project.msrchd.${domain}"
      cert_dir="/var/lib/acme/$subdomain"

      # Get display title from .title file, or use project name
      if [ -f "$PROJECTS_DIR/$project/.title" ]; then
        title=$(cat "$PROJECTS_DIR/$project/.title")
      else
        title="$project"
      fi

      # Get description from .description.html (HTML) or .description (plain text)
      if [ -f "$PROJECTS_DIR/$project/.description.html" ]; then
        description=$(cat "$PROJECTS_DIR/$project/.description.html")
        description_is_html="true"
      elif [ -f "$PROJECTS_DIR/$project/.description" ]; then
        description=$(cat "$PROJECTS_DIR/$project/.description")
        description_is_html="false"
      else
        description="No description available."
        description_is_html="false"
      fi

      if [ -f "$cert_dir/fullchain.pem" ]; then
        url="https://$subdomain/"
      else
        url="http://$subdomain/"
      fi

      if [ "$description_is_html" = "true" ]; then
        cat >> "$INDEX_FILE" << INDEX_PROJECT_HTML
    <div class="project" onclick="this.classList.toggle('expanded')">
      <div class="project-header">
        <span class="project-title"><i class="fas fa-flask icon"></i>$title</span>
        <i class="fas fa-chevron-down project-toggle"></i>
      </div>
      <div class="project-body">
        <div class="project-description">
          $description
          <a href="$url" class="project-link" onclick="event.stopPropagation()">
            <span>See experiment results</span>
            <i class="fas fa-arrow-right"></i>
          </a>
        </div>
      </div>
    </div>
INDEX_PROJECT_HTML
      else
        cat >> "$INDEX_FILE" << INDEX_PROJECT_TEXT
    <div class="project" onclick="this.classList.toggle('expanded')">
      <div class="project-header">
        <span class="project-title"><i class="fas fa-flask icon"></i>$title</span>
        <i class="fas fa-chevron-down project-toggle"></i>
      </div>
      <div class="project-body">
        <div class="project-description">
          <p>$description</p>
          <a href="$url" class="project-link" onclick="event.stopPropagation()">
            <span>See experiment results</span>
            <i class="fas fa-arrow-right"></i>
          </a>
        </div>
      </div>
    </div>
INDEX_PROJECT_TEXT
      fi
    done

    if [ -z "$PROJECTS" ]; then
      echo "    <p class=\"empty\">No experiments yet.</p>" >> "$INDEX_FILE"
    fi

    cat >> "$INDEX_FILE" << 'INDEX_FOOTER'
    </div>
  </div>

  <div id="about" class="tab-content">
    <h2>About msrchd</h2>
    <div class="about">
      <p>
        <strong>msrchd</strong> aims to be a less-featureful version of
        <a href="https://github.com/dust-tt/srchd">dust-tt/srchd</a> for small personal experiments - the "mini" srchd.
      </p>

      <h3>How it works</h3>
      <p>
        msrchd orchestrates AI research agents through a publication and peer review system.
        Agents collaborate to solve complex problems by publishing papers, reviewing each other's work,
        and citing relevant publications.
      </p>

      <h3>Key Features</h3>
      <ul>
        <li><strong>Multi-agent collaboration</strong> - Run multiple AI agents that work together on research problems</li>
        <li><strong>Publication system</strong> - Agents submit papers for peer review</li>
        <li><strong>Peer review</strong> - Agents review each other's work with accept/reject decisions</li>
        <li><strong>Citation tracking</strong> - Track which publications cite others to identify impactful work</li>
        <li><strong>Solution voting</strong> - Agents vote for the best solution to the problem</li>
        <li><strong>Isolated execution</strong> - Each agent runs in a Docker container with full filesystem access</li>
        <li><strong>Cost tracking</strong> - Track token usage and costs per experiment</li>
      </ul>

      <h3>Design Philosophy</h3>
      <p>
        This version strips away complexity to focus on the core collaboration mechanism:
        single model per experiment, simplified agent profiles, unified tool set, and
        Docker-based isolation instead of Kubernetes orchestration.
      </p>
      <p>
        The goal: <strong>maximum collaboration effectiveness with minimum configuration complexity</strong>.
      </p>
    </div>
  </div>

  <script>
    // Tab switching
    document.querySelectorAll('.tab-link').forEach(link => {
      link.addEventListener('click', (e) => {
        e.preventDefault();
        const tab = link.dataset.tab;

        // Update active states
        document.querySelectorAll('.tab-link').forEach(l => l.classList.remove('active'));
        document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));

        link.classList.add('active');
        document.getElementById(tab).classList.add('active');

        // Update URL hash
        history.pushState(null, null, '#' + tab);
      });
    });

    // Handle initial hash
    if (window.location.hash) {
      const tab = window.location.hash.slice(1);
      const link = document.querySelector('[data-tab="' + tab + '"]');
      if (link) link.click();
    }
  </script>
</body>
</html>
INDEX_FOOTER

    echo "=== Discovery complete ==="
  '';

  # Script to read port from project directory
  getPortScript = pkgs.writeShellScriptBin "msrchd-get-port" ''
    PROJECT="$1"
    PORT_FILE="${projectsDir}/$PROJECT/.port"
    if [ -f "$PORT_FILE" ]; then
      cat "$PORT_FILE"
    else
      echo "${toString basePort}"
    fi
  '';

in
{
  # Install required packages
  environment.systemPackages = with pkgs; [
    nodejs
    git
    certbot
    discoveryScript
    getPortScript
  ];

  # Create directories
  systemd.tmpfiles.rules = [
    "d ${msrchdBase} 0755 root root -"
    "d ${projectsDir} 0755 root root -"
    "d ${acmeChallengeDir} 0755 root root -"
  ];

  # Base installation service (one-time setup)
  systemd.services.msrchd-base = {
    description = "msrchd base installation";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];

    path = [ pkgs.bash pkgs.coreutils pkgs.git nodejs ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };

    script = ''
      # Clone msrchd repo if not present
      if [ ! -d "${msrchdBase}/.git" ]; then
        ${pkgs.git}/bin/git clone https://github.com/anonx3247/msrchd.git ${msrchdBase}
      fi

      # Install dependencies if node_modules doesn't exist
      cd ${msrchdBase}
      if [ ! -d "${msrchdBase}/node_modules" ]; then
        ${nodejs}/bin/npm install --production=false
      fi
    '';
  };

  # Template service for per-project msrchd instances
  systemd.services."msrchd@" = {
    description = "msrchd experiment viewer - %i";
    after = [ "network.target" "msrchd-base.service" ];
    requires = [ "msrchd-base.service" ];

    path = [ pkgs.bash pkgs.coreutils nodejs getPortScript ];

    serviceConfig = {
      Type = "simple";
      WorkingDirectory = "${projectsDir}/%i";
      ExecStart = "${pkgs.bash}/bin/bash -c '${nodejs}/bin/node ${msrchdBase}/node_modules/.bin/tsx ${msrchdBase}/src/srchd.ts serve -p $(msrchd-get-port %i) ${authArgs}'";
      Restart = "always";
      RestartSec = 10;

      Environment = [
        "NODE_ENV=production"
        "HOME=${projectsDir}/%i"
        "PUBLICATIONS_DIR=${projectsDir}/%i/publications"
      ];

      EnvironmentFile = "/etc/srchd/env";

      # Run migrations before starting (using ExecStartPre with specifier)
      ExecStartPre = "${pkgs.bash}/bin/bash -c 'cd ${projectsDir}/%i && ${nodejs}/bin/node ${msrchdBase}/node_modules/.bin/drizzle-kit migrate || true'";
    };
  };

  # Discovery timer - runs periodically to find new projects
  systemd.timers.msrchd-discover = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnBootSec = "1min";
      OnUnitActiveSec = "5min";
      Unit = "msrchd-discover.service";
    };
  };

  systemd.services.msrchd-discover = {
    description = "Discover and configure msrchd projects";
    after = [ "msrchd-base.service" "nginx.service" ];
    requires = [ "msrchd-base.service" ];

    path = [ pkgs.bash pkgs.coreutils pkgs.systemd pkgs.gnugrep pkgs.gawk pkgs.certbot ];

    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${discoveryScript}/bin/msrchd-discover";
    };
  };

  # Main msrchd.domain nginx - serves index page
  services.nginx.virtualHosts."msrchd.${domain}" = {
    enableACME = true;
    forceSSL = true;

    root = msrchdBase;

    locations."/" = {
      index = "index.html";
    };
  };

  # Include dynamic project configs
  services.nginx.appendHttpConfig = ''
    include /etc/nginx/msrchd-projects.conf;
  '';

  # Ensure the include file exists (empty initially)
  system.activationScripts.msrchd-nginx-conf = ''
    mkdir -p /etc/nginx
    touch /etc/nginx/msrchd-projects.conf
  '';
}
