# Auto-generated NixOS configuration
# Generated by setup.sh
# DO NOT EDIT DIRECTLY - Edit base_configuration.nix instead

{ config, lib, pkgs, ... }:

let
  # Users defined in users.txt
  definedUsers = [
    "anas"     "paul"     "assia"     "safa"     "aymen"     "suleiman"     "evelyne"
  ];

  # Domain configuration
  domainName = "lecaillon.com";
  webDomainPrefix = "anas";

  # Service configuration
  enableMail = true;
  enableGit = false;
  enableWeb = true;
  enableSrchd = true;
  enableMsrchd = true;
  enableIbnmalik = true;
  enableTailscale = true;
  enableSearx = false;
  srchdAuthCredentials = "";
in

import ./base_configuration.nix {
  inherit config lib pkgs;
  users = definedUsers;
  domain = domainName;
  webPrefix = webDomainPrefix;
  srchdAuth = srchdAuthCredentials;
  services = {
    mail = enableMail;
    git = enableGit;
    web = enableWeb;
    srchd = enableSrchd;
    msrchd = enableMsrchd;
    ibnmalik = enableIbnmalik;
    tailscale = enableTailscale;
    searx = enableSearx;
  };
}
